---
- name: Update APT cache
  apt:
    upgrade: yes
    update_cache: yes
  become: true

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Install essential packages
  apt:
    name: '{{ item }}'
  with_items:
    - build-essential
    - ruby
    - ruby-dev
    - ruby-bundler
    - mysql-client
    - mysql-server
    - libmysqlclient-dev
    - libxml2-dev
    - libmagickcore-dev
    - libmagickwand-dev
  become: true

- name: Setup Redmine source code
  git:
    repo: 'https://github.com/redmine/redmine.git'
    dest: /home/hiroshiyui/redmine
    version: '3.4.4'

- name: Setup redmine-trello-card-sync source code
  git:
    repo: 'git@github.com:hiroshiyui/redmine-trello-card-sync.git'
    dest: /home/hiroshiyui/redmine/plugins/redmine_trello_card_sync
