---
- hosts: 127.0.0.1
  connection: local
  vars:
    zone: asia-northeast1-a
  tasks:
    - name: Create a GCE instance
      gce:
        name: 'my-gce-openvpn-{{ zone }}'
        zone: '{{ zone }}'
        num_instances: 1
        machine_type: f1-micro
        image: ubuntu-1604-xenial-v20180112
        image_family: ubuntu-1604-lts
        state: present
        disk_size: 10
        ip_forward: yes
        tags:
          - openvpn-server
      register: gce

    - name: Debug
      debug:
        msg: '{{ gce }}'

    - name: Add host to a group
      add_host:
        hostname: '{{ item.public_ip }}'
        groupname: my-gce-openvpn
      with_items: '{{ gce.instance_data }}'

    - name: Wait for SSH
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

    - name: Setup GCP firewall rules
      gce_net:
        name: default
        fwname: openvpn-server
        allowed: udp:1194
        state: present
        src_range:
          - '0.0.0.0/0'
        target_tags:
          - openvpn-server

- name: Setup OpenVPN
  hosts: my-gce-openvpn
  roles:
    - Stouts.openvpn
    - openvpn-server
  become: true
  gather_facts: yes
  vars:
    openvpn_key_size: 2048
    openvpn_use_pam: yes
    openvpn_clients:
      - my-gce-openvpn
    openvpn_server_options:
      - 'management 127.0.0.1 9801'
      - 'tun-mtu 1500'
      - 'mssfix 1300'
      - 'push "redirect-gateway def1 bypass-dhcp"'
    openvpn_client_options:
      - 'tun-mtu 1500'
      - 'mssfix 1300'